"""
Indicates an Input Object is a OneOf Input Object.
"""
directive @oneOf on INPUT_OBJECT

type Query {
  defaultImage: Image!
  images(
    """
    Returns the items in the list that come before the specified cursor.
    """
    before: String = null

    """
    Returns the items in the list that come after the specified cursor.
    """
    after: String = null

    """
    Returns the first n items from the list.
    """
    first: Int = null

    """
    Returns the items in the list that come after the specified cursor.
    """
    last: Int = null
  ): ImageConnection!
  defaultPairs: ThinSectionImagePairs!
  getPairs(pairsCode: String!, sampleId: String!): ThinSectionImagePairs!
}

type Image implements Node {
  """
  The Globally Unique ID of this object
  """
  id: ID!
  path: String!
  width: Int!
  height: Int!
  thumbnailPath: String
  url: String!
  thumbnailUrl: String
}

"""
An object with a Globally Unique ID
"""
interface Node {
  """
  The Globally Unique ID of this object
  """
  id: ID!
}

"""
A connection to a list of items.
"""
type ImageConnection {
  """
  Pagination data for this connection
  """
  pageInfo: PageInfo!

  """
  Contains the nodes in this connection
  """
  edges: [ImageEdge!]!
}

"""
Information to aid in pagination.
"""
type PageInfo {
  """
  When paginating forwards, are there more items?
  """
  hasNextPage: Boolean!

  """
  When paginating backwards, are there more items?
  """
  hasPreviousPage: Boolean!

  """
  When paginating backwards, the cursor to continue.
  """
  startCursor: String

  """
  When paginating forwards, the cursor to continue.
  """
  endCursor: String
}

"""
An edge in a connection.
"""
type ImageEdge {
  """
  A cursor for use in pagination
  """
  cursor: String!

  """
  The item at the end of the edge
  """
  node: Image!
}

type ThinSectionImagePairs implements Node {
  """
  The Globally Unique ID of this object
  """
  id: ID!
  sampleId: String!
  label: String
  description: String
  AcquiredCache: [AcquiredImage!]
  PolarizedFilterTypes: [PolarizedFilterType!]
  Gammas: [Int!]
  acquiredImages: [AcquiredImage!]!
  imageByAcquisition(acquisitionType: PolarizedFilterType!): Image
  polarizedFilterTypes: [PolarizedFilterType!]!
  gammas: [Int]!
}

type AcquiredImage {
  polarizedFilterType: PolarizedFilterType!
  gamma: Int
  acquisitionLabel: String
  image: Image!
}

enum PolarizedFilterType {
  PPL
  XPL
  XPL_GAMMA
  OTHER
}

type Mutation {
  startSessionImage(input: StartSessionInput!): StartSession!
  addPointsImage(input: AddPointsImageInput!): RLEMaskListOnFrame!
  computeSlicImage(input: SlicImageInput!): RLEMaskListOnFrame!
  saveAnnotations(input: AddPointsImageInput!): SaveAnnotationsResult!
}

type StartSession {
  sessionId: String!
}

input StartSessionInput {
  path: String!
  pairsCode: ID!
  sampleId: String!
}

type RLEMaskListOnFrame {
  frameIndex: Int!
  rleMaskList: [RLEMaskForObject!]!
}

type RLEMaskForObject {
  objectId: Int!
  rleMask: RLEMask!
}

type RLEMask {
  size: [Int!]!
  counts: String!
  order: String!
}

input AddPointsImageInput {
  sessionId: String!
  imagePath: String!
  imageId: ID!
  objectId: Int!
  labels: [Int!]!
  points: [[Float!]!]!
  bboxes: [[Float!]!]!
}

input SlicImageInput {
  sessionId: String!
  imagePath: String!
  imageId: ID!
  bbox: [Float!]!
}

type SaveAnnotationsResult {
  success: Boolean!
}
